# -*- coding: utf-8 -*-
"""flower-classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1xngDka6SVyrsnBJUxzm4OQV-saWHlx

## Import
"""

import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib
import numpy as np

"""## Load Data"""

df = pd.read_csv('Iris.csv')

df.head()

x = df.iloc[:, 1:5]
y = df['Species']

x, y

"""## Split Data"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

"""## Modelling with Random Forest Classifier"""

model = RandomForestClassifier()

model.fit(x_train, y_train)

model.score(x_train, y_train)

"""## Evaluate"""

predictions = model.predict(x_test)
predictions[:10]

print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

"""## Save Model"""

joblib.dump(model, 'randomforest_model.pkl')

test_data = [5.1, 3.2, 1.5, 0.4]

#convert test_data into numpy array
test_data = np.array(test_data)

#reshape
test_data = test_data.reshape(1,-1)
print(test_data)

"""## Predict & Load Save Model"""

#declare path where you saved your model
filePath = 'randomforest_model.pkl'

#open file
file = open(filePath, "rb")

#load the trained model
trained_model = joblib.load(file)

prediction = trained_model.predict(test_data)
print(prediction)